### ISSUE TITLE
The web call to retrieve ipv4 addresses now returns 61 entries, breaking security groups in AWS

### ISSUE THREAD

**Issue by brunzefb** [terra-mod/terraform-bitbucket-ip-addresses#3]
Bitbucket now has 61 IPV4 addresses, which breaks the max # of IP's per security group.

╷
│ Error: Error authorizing security group rule type ingress: RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.
│       status code: 400

**Comment by k-k** [comment]
@brunzefb This technically wasn't the responsibility of this module - as a consumer may be using something different than AWS SGs and, even if they were, had the option to chunk the list returned in their usage.

That said, I added two new outputs that will chunk the list of ip addresses returned by a configurable size. Making it a map versus a list makes it easier to use `for_each` (instead of `count`) to dynamically create the desired number of SGs. I updated the readme with an example.

**Comment by n1ngu** [comment]
Years ago, Atlassian's address list length also used to be this long.

My way to go with AWS security groups was to request enlarging the limits in my account.

Having https://www.terraform.io/language/functions/chunklist I do not see either why chunking should happen in this module. For sure it will come handy for a bunch of people, but defeats software design best practices.
